let mongoose = require('mongoose');
let Schema = mongoose.Schema;

let UserSchema = new Schema({
    username: {
        type: String,
        required: true,
        unique: true
    },
    firstname: {
        type: String,
    },
    lastname: {
        type: String,
    },
    password: {
        type: String,
        required: true,
        trim: true
    },
    email: {
        type: String,
        required: true,
        unique: true,
        trim: true
    },
    emailverified: {
        type: Boolean,
        required: true,
        default: false
    },
    address: {
        addressOne: {
            type: String,
            trim: true
        },
        // Appartment, Studio, or Floor.
        addressTwo: {
            type: String,
            trim: true
        },
        city: {
            type: String,
            trim: true
        },
        state: {
            type: String,
            trim: true
        },    
        zip: {
            type: String,
            trim: true
        }
    },
    salt: {
        type: String
    },
    publickey : {
        type: String
    },
    txid: [{
        type: String,
        unique: true
    }],
    orders : [
        //_id should be autogenerated for an object in an array.
        {
            currency: {
                type: String,
                required: true
            },
            amountRecieved: {
                type: Number,
                required: true
            }
        }]
}, {
    timestamps: { createdAt: 'created_at' }
    
});

let User = mongoose.model("User", UserSchema);
module.exports = User;