let mongoose = require('mongoose');
let Schema = mongoose.Schema;

let UserSchema = new Schema({
    name: {
        type: String,
        required: true,
        unique: true
    },
    password: {
        type: String,
        required: true,
        trim: true
    },
    email: {
        type: String,
        required: true,
        unique: true,
        trim: true
    },
    salt: {
        type: String
    },
    publickey : {
        type: String
    },
    orders : [
        //_id should be autogenerated for an object in an array.
        {
            currency: {
                type: String,
                required: true
            },
            amountRecieved: {
                type: Number,
                required: true
            }
        }]
}, {
    timestamps: { createdAt: 'created_at' }
    
});

let User = mongoose.model("User", UserSchema);
module.exports = User;